-- scenes 테이블에 캐릭터 슬롯 2~4 추가
ALTER TABLE public.scenes
  ADD COLUMN IF NOT EXISTS character2 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS character3 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS character4 TEXT DEFAULT NULL;
